#!/usr/bin/env python3
"""Build appendix assets from the unblurred website/arXiv PNG export (png_assets/).
    python3 tools/web_assets/build_web_assets.py <path/to/png_assets>
Writes assets/images/appendix/{sites,objects}/ and the three figure bodies
figures/fig_capture_sites.tex and figures/fig_object_gallery.tex.
No blur, sharpening or generative edits; images are only cropped and downsampled
(never upscaled)."""
import csv, json, os, sys
import numpy as np
from PIL import Image
SRC = sys.argv[1]
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
A = os.path.join(ROOT, 'assets', 'images', 'appendix')
meta = {r['scene_id']: r for r in csv.DictReader(open(os.path.join(ROOT, 'tools', 'catalogue_frames', 'scene_metadata.csv')))}

# ---------------------------------------------------------------- capture sites
DESC = {1: 'fountain plinth steps', 2: 'round table by windows', 3: 'sofa lounge', 4: 'checkerboard dining table',
        5: 'carpeted stairs', 6: 'deck table with umbrella', 7: 'sitting area', 8: 'lecture hall table',
        9: 'picnic bench', 10: 'shaded brick steps', 11: 'tennis court', 12: 'lounge benches',
        13: 'atrium seating block', 14: 'tall white table', 15: 'atrium stairs', 16: 'round lounge table',
        17: 'garden planter', 18: 'atrium bench', 19: 'stone bench', 20: 'rock garden'}
bgs = sorted(f for f in os.listdir(os.path.join(SRC, 'backgrounds')) if f.endswith('.png'))
assert len(bgs) == 20
os.makedirs(os.path.join(A, 'sites'), exist_ok=True)
cells = []
for k, f in enumerate(bgs, 1):
    im = Image.open(os.path.join(SRC, 'backgrounds', f)).convert('RGB'); W, H = im.size
    w, h = (W, W * 3 // 4) if W * 3 <= H * 4 else (H * 4 // 3, H)          # centred 4:3 crop
    im = im.crop(((W - w) // 2, (H - h) // 2, (W - w) // 2 + w, (H - h) // 2 + h))
    if w > 1200: im = im.resize((1200, 900), Image.Resampling.LANCZOS)
    im.save(os.path.join(A, 'sites', f'site{k:02d}.jpg'), quality=90, subsampling=0)
    sc = [f'scene{i:03d}' for i in range(5 * k - 4, 5 * k + 1)]
    env = {meta[s]['environment'] for s in sc}; assert len(env) == 1
    cells.append((k, env.pop().capitalize(), DESC[k], sc[0][5:], sc[-1][5:]))
T = [r'''% Generated by tools/web_assets/build_web_assets.py -- capture-site photographs (4:3 crops).
\begin{tikzpicture}[x=1cm,y=1cm]
\def\sw{4.305}\def\sh{3.229}\def\sg{0.12}\def\sl{0.78}''']
for i, (k, env, d, a, b) in enumerate(cells):
    c, r = i % 4, i // 4
    x, y = c * (4.305 + 0.12), -r * (3.229 + 0.78)
    T.append(rf'\node[anchor=north west,inner sep=0pt] at ({x:.3f},{y:.3f}) {{\includegraphics[width=\sw cm,height=\sh cm]{{assets/images/appendix/sites/site{k:02d}.jpg}}}};')
    T.append(rf'\draw[rpxAccent,line width=.35pt] ({x:.3f},{y:.3f}) rectangle ++(\sw,-\sh);')
    T.append(rf'\node[anchor=north west,inner sep=0pt,font=\footnotesize] at ({x:.3f},{y - 3.229 - 0.1:.3f}) {{\textbf{{Site {k}}}\enspace {env}}};')
    T.append(rf'\node[anchor=north east,inner sep=0pt,font=\fontsize{{7.5}}{{9}}\selectfont,text=rpxSlate] at ({x + 4.305:.3f},{y - 3.229 - 0.1:.3f}) {{scenes {a}--{b}}};')
    T.append(rf'\node[anchor=north west,inner sep=0pt,font=\fontsize{{7.5}}{{9}}\selectfont,text=rpxSlate] at ({x:.3f},{y - 3.229 - 0.44:.3f}) {{{d}}};')
T.append(r'\end{tikzpicture}')
open(os.path.join(ROOT, 'figures', 'fig_capture_sites.tex'), 'w').write('\n'.join(T) + '\n')

# ---------------------------------------------------------------- object gallery
rows = list(csv.DictReader(open(os.path.join(SRC, 'objects.csv'))))
cat = {int(n): name for n, name, _ in json.load(open(os.path.join(ROOT, 'tools', 'catalogue', 'catalogue_canonical.json')))}
assert [int(r['id']) for r in rows] == list(range(1, 71))
os.makedirs(os.path.join(A, 'objects'), exist_ok=True)
BOX_IN, FLOOR_DPI, BG = 0.74, 200, (244, 245, 247)
for r in rows:
    im = Image.open(os.path.join(SRC, r['cutout'])).convert('RGBA')
    bb = im.getchannel('A').getbbox(); im = im.crop(bb)
    side = max(im.size); canvas = max(int(side * 1.06), int(BOX_IN * FLOOR_DPI))   # never upscale
    bgc = Image.new('RGBA', (canvas, canvas), BG + (255,))
    bgc.alpha_composite(im, ((canvas - im.width) // 2, (canvas - im.height) // 2))
    bgc.convert('RGB').save(os.path.join(A, 'objects', f'obj{int(r["id"]):02d}.jpg'), quality=92, subsampling=0)
T = [r'''% Generated by tools/web_assets/build_web_assets.py -- all 70 SOS objects, segmented with
% their released instance masks, numbered as in the canonical catalogue.
\begin{tikzpicture}[x=1cm,y=1cm]
\def\ow{1.88}\def\og{0.1}\def\ol{0.62}''']
for i, r in enumerate(rows):
    n = int(r['id']); c, q = i % 9, i // 9
    x, y = c * (1.88 + 0.1), -q * (1.88 + 0.62)
    T.append(rf'\node[anchor=north west,inner sep=0pt] at ({x:.3f},{y:.3f}) {{\includegraphics[width=\ow cm,height=\ow cm]{{assets/images/appendix/objects/obj{n:02d}.jpg}}}};')
    T.append(rf'\node[anchor=north west,inner sep=0pt,text width=\ow cm,align=left,font=\fontsize{{7.5}}{{8.6}}\selectfont] at ({x:.3f},{y - 1.88 - 0.07:.3f}) {{\textbf{{{n}}}\enspace {cat[n]}}};')
T.append(r'\end{tikzpicture}')
open(os.path.join(ROOT, 'figures', 'fig_object_gallery.tex'), 'w').write('\n'.join(T) + '\n')

small = [int(r['id']) for r in rows if max(Image.open(os.path.join(SRC, r['cutout'])).getchannel('A').getbbox()[2:]) < BOX_IN * FLOOR_DPI]
print('sites', len(cells), '| objects 70 | cutouts below 200-dpi fill (shown smaller, not upscaled):', small)
