from .base import BaseBenchmark

from .relative_camera_pose import RelativePoseBenchmark, RelativePoseDataset
from .visual_grounding import VisualGroundingBenchmark, VisualGroundingDataset
from .depth_estimation import DepthEstimationBenchmark, DepthEstimationDataset
from .object_tracking import ObjectTrackingBenchmark, ObjectTrackingDataset
from .novel_view_synthesis import NovelViewSynthesisBenchmark, NovelViewSynthesisDataset
