#!/usr/bin/env python3
"""Build generated/scene_objects_table.tex: objects present in each MOS scene,
as SOS catalogue IDs (identical in all three exocentric phases)."""
import csv, os, collections
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(os.path.dirname(HERE))
meta = {r['scene_id']: r for r in csv.DictReader(open(os.path.join(HERE, 'scene_metadata.csv')))}
objs = collections.defaultdict(set)
for r in csv.DictReader(open(os.path.join(HERE, 'mos_mask_object_map_v1.csv'))):
    if r['phase'] == 'phase0': objs[r['scene_id']].add(int(r['global_object_id']))
T = {'easy': ('tierE', 'Easy'), 'medium': ('tierM', 'Medium'), 'hard': ('tierH', 'Hard')}
head = r'Scene & Environment & Tier & Objects (catalogue IDs) \\'
L = ['% Generated by tools/catalogue_frames/build_scene_objects.py -- do not edit by hand.',
     r'\par\begingroup\centering\footnotesize\setlength{\tabcolsep}{3pt}\renewcommand{\arraystretch}{1.02}',
     r'\tablefirsthead{\toprule ' + head + r' \midrule}',
     r'\tablehead{\multicolumn{4}{@{}c@{}}{\footnotesize TABLE~\ref{tab:appendix-scene-objects} (continued)}\\[3pt]\toprule ' + head + r' \midrule}',
     r'\tabletail{\bottomrule}', r'\tablelasttail{\bottomrule}',
     r'\topcaption{Objects in each MOS scene, listed by their SOS catalogue ID (Table~\ref{tab:sos-canonical}); the set is identical in all three exocentric phases.}\label{tab:appendix-scene-objects}',
     r'\begin{supertabular}{@{}l l l >{\raggedright\arraybackslash}p{\dimexpr\columnwidth-4.6cm\relax}@{}}']
for s in sorted(meta):
    m = meta[s]; c, t = T[m['tier']]
    L.append(f"{s[5:]} & {m['environment'].capitalize()} & \\textcolor{{{c}}}{{{t}}} & {', '.join(str(i) for i in sorted(objs[s]))} \\\\")
L += [r'\end{supertabular}\par\endgroup\medskip']
open(os.path.join(ROOT, 'generated', 'scene_objects_table.tex'), 'w').write('\n'.join(L) + '\n')
print('scenes', len(meta), 'objects/scene', sorted(collections.Counter(len(v) for v in objs.values()).items()))
