#!/usr/bin/env python3
"""Build generated/scene_catalogue.tex: the complete 100-scene MOS catalogue.

One scene per row (scene label, then Clutter / Interaction / Clean / Ego),
ROWS scenes per full-width float page. Each cell reads
assets/images/appendix/catalogue/<scene>_<view>.jpg (view in 0,1,2,ego); a cell
whose image is absent prints a neutral fixed-size 'image pending' panel of the
same size, so adding images later never reflows the document."""
import csv, os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(os.path.dirname(HERE))
# rows per catalogue page: 9 pages of 8 and 4 of 7 fill all 13 pages (no partial page)
PAGE_ROWS = [8] * 9 + [7] * 4
meta = list(csv.DictReader(open(os.path.join(HERE, 'scene_metadata.csv'))))
TIER = {'easy': ('tierE', 'Easy'), 'medium': ('tierM', 'Medium'), 'hard': ('tierH', 'Hard')}
out = ['% Generated by tools/catalogue_frames/build_scene_catalogue.py -- do not edit by hand.']
assert sum(PAGE_ROWS) == len(meta)
chunks, k = [], 0
for n in PAGE_ROWS: chunks.append(meta[k:k + n]); k += n
for ci, ch in enumerate(chunks):
    last = ci == len(chunks) - 1
    out.append('\\begin{figure*}[p]')
    if ci: out.append('\\ContinuedFloat')
    out.append('\\centering\\catheader')
    out.append('\\setlength\\catRowSep{%s}' % ('\\catG' if len(ch) == 8 else '16.1pt'))
    for r in ch:
        col, lab = TIER[r['tier']]
        out.append('\\catrow{%s}{%s}{%s}{%s}' % (r['scene_id'][5:], r['environment'].capitalize(), col, lab))
    a, b = ch[0]['scene_id'][5:], ch[-1]['scene_id'][5:]
    if ci == 0:
        out.append('\\caption{Complete multi-object scene catalogue, scenes %s--%s. Each row shows the middle frame of the Clutter, Interaction, and Clean exocentric captures and of the egocentric Interaction clip.}' % (a, b))
        out.append('\\label{fig:appendix-scene-catalogue}')
    else:
        out.append('\\caption[]{Complete multi-object scene catalogue (continued), scenes %s--%s.}' % (a, b))
    out.append('\\end{figure*}')
open(os.path.join(ROOT, 'generated', 'scene_catalogue.tex'), 'w').write('\n'.join(out) + '\n')
print(len(chunks), 'catalogue pages')
