#!/usr/bin/env python3
"""Build generated/desirability_table.tex and generated/model_config_table.tex
from tools/protocol/desirability_windows.csv and model_config.csv.
An empty CSV cell (or ---) prints as an em dash."""
import csv, os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(os.path.dirname(HERE))
def c(v): v = (v or '').strip(); return v if v and v != '---' else '---'
ARROW = {'higher': '$\\uparrow$', 'lower': '$\\downarrow$'}
BASIS = {'range': 'range', 'fixed': 'fixed', '': '---'}
rows = list(csv.DictReader(open(os.path.join(HERE, 'desirability_windows.csv'))))
# In-flow column blocks so the table always follows its subsection text and
# precedes the raw-metric tables.
import sys
sys.path.insert(0, os.path.dirname(HERE))
import blocktable
groups, prev = [], None
for r in rows:
    g = f"{r['metric_tex']} & {r['tasks'].replace(' ', ', ')} & {c(r['worse'])} & {c(r['better'])} & {ARROW[r['direction']]} & {BASIS[r['basis'].strip()]}"
    groups.append(g)
blocktable.write('desirability', 'tab:appendix-desirability',
    'Desirability windows of all native metrics. $d_k=0$ at the worse endpoint and $1$ at the better endpoint; range: natural bounds of the metric; fixed: frozen error cap shared by all models.',
    '@{}l@{\\extracolsep{\\fill}}lcccc@{}'.replace('@{\\extracolsep{\\fill}}',''), 'Metric & Task(s) & Worse & Better & Dir. & Basis \\\\', groups, '',
    '\\footnotesize\\setlength{\\tabcolsep}{4.2pt}', os.path.join(ROOT, 'generated', 'desirability_table.tex'))
_p = os.path.join(ROOT, 'generated', 'desirability_table.tex')
_body = open(_p).read()
open(_p, 'w').write('% TODO CAMERA READY: fill the unresolved (em-dash) VQA desirability endpoints before submission.\n' + _body)
rows = list(csv.DictReader(open(os.path.join(HERE, 'model_config.csv'))))
L = ['% Generated by tools/protocol/build_protocol_tables.py -- do not edit by hand.',
     '% TODO CAMERA READY: fill the unresolved (em-dash) configuration fields before submission.',
     '\\begin{table*}[t]', '\\centering',
     '\\caption{Evaluation configuration of every model--task evaluation, beyond what main-paper Tables~\\ref{tab:t1}--\\ref{tab:vqa} list.}',
     '\\label{tab:appendix-model-config}', '\\footnotesize', '\\setlength{\\tabcolsep}{3.5pt}', '\\renewcommand{\\arraystretch}{1.04}',
     '\\begin{tabular}{@{}l>{\\raggedright\\arraybackslash}p{4.6cm}>{\\raggedright\\arraybackslash}p{3.1cm}>{\\raggedright\\arraybackslash}p{3.4cm}>{\\raggedright\\arraybackslash}p{4.9cm}@{}}',
     '\\toprule', 'Task & Configurations & Input handling & Initialization / prompt & Alignment / special setting \\\\', '\\midrule']
prev = None
for r in rows:
    if prev and r['task'] != prev: L.append('\\addlinespace[2pt]')
    prev = r['task']
    L.append(' & '.join(c(r[k]) for k in ['task', 'configurations', 'input', 'init_prompt', 'setting']) + ' \\\\')
L += ['\\bottomrule', '\\end{tabular}', '\\end{table*}']
open(os.path.join(ROOT, 'generated', 'model_config_table.tex'), 'w').write('\n'.join(L) + '\n')
print('built desirability_table.tex, model_config_table.tex')
